#!/usr/bin/python3

import subprocess
import time
import sys

import tester, monitor, action


if __name__ == "__main__":
        
    if len(sys.argv) <= 2:
        log.error("Expected: <action>[:key=value,... | value,...] <command>[:key=value,... | value,...] ...")
        sys.exit(1)

    #parse action string
    act = action.parse(sys.argv[1])
    if not act:
        log.error("Action not recognised")
    
    #parse test string(s)
    tests = [tester.parse(a) for a in sys.argv[2:]]
    if not tests:
        log.error("Command not recognised")
        sys.exit(2)
    test = tester.AndTester(tests)

    #construct monitor    
    lockmon = monitor.PollMonitor(test, act, always=True)
    lockmon.start()

